#!/usr/bin/env node

module.exports = function (context) {
	
	var path = context.requireCordovaModule('path');
    var platformRoot = path.join(context.opts.projectRoot, '/platforms/windows/');
	var fs = context.requireCordovaModule('fs');

	function copyFileSync(srcFile, destFile, encoding) {
		var content = fs.readFileSync(platformRoot + srcFile, encoding);
		fs.writeFileSync(platformRoot + destFile, content, encoding);
	}

	//We need to create a Windows 8 appxmanifest file because the cordova-plugin-customurlscheme plugin wants to edit it
	//The Windows 8 appxmanifest is not generated by the Cordova yet so the plugin should not edit it
	//If the plugin is updated then this copy should be removed
	copyFileSync("package.windows.appxmanifest", "package.windows80.appxmanifest", "UTF-8");
};